export default {
  ARTS_PHOTOGRAPHY: 'Arts & Photography',
  BIOGRAPHIES_MEMOIRS: 'Biographies & Memoirs',
  BUSINESS_MONEY: 'Business & Money',
  CALENDARS: 'Calendars',
  CHILDREN_BOOKS: 'Children\'s Books',
  CHRISTIAN_BOOKS_BIBLES: 'Christian Books & Bibles',
  COMICS_GRAPHIC_NOVELS: 'Comics & Graphic Novels',
  COMPUTERS_TECHNOLOGY: 'Computers & Technology',
  COOKBOOKS_FOOD_WINE: 'Cookbooks, Food & Wine',
  CRAFTS_HOBBIES_HOME: 'Crafts, Hobbies & Home',
  EDUCATION_TEACHING: 'Education & Teaching',
  ENGINEERING_TRANSPORTATION: 'Engineering & Transportation',
  HEALTH_FITNESS_DIETING: 'Health, Fitness & Dieting',
  HISTORY: 'History',
  HUMOR_ENTERTAINMENT: 'Humor & Entertainment',
  LAW: 'Law',
  LGBTQ_BOOKS: 'LGBTQ+ Books',
  LITERATURE_FICTION: 'Literature & Fiction',
  MEDICAL_BOOKS: 'Medical Books',
  MYSTERY_THRILLER_SUSPENSE: 'Mystery, Thriller & Suspense',
  PARENTING_RELATIONSHIPS: 'Parenting & Relationships',
  POLITICS_SOCIAL_SCIENCES: 'Politics & Social Sciences',
  REFERENCE: 'Reference',
  RELIGION_SPIRITUALITY: 'Religion & Spirituality',
  ROMANCE: 'Romance',
  SCIENCE_MATH: 'Science & Math',
  SCIENCE_FICTION_FANTASY: 'Science Fiction & Fantasy',
  SELF_HELP: 'Self-Help',
  SPORTS_OUTDOORS: 'Sports & Outdoors',
  TEEN_YOUNG_ADULT: 'Teen & Young Adult',
  TEST_PREPARATION: 'Test Preparation',
  TRAVEL: 'Travel',
};
