const genre = {
  Arts_Photography: 'Arts & Photography',
  Biographies_Memoirs: 'Biographies & Memoirs',
  Business_Money: 'Business & Money',
  Calendars: 'Calendars',
  Children_Books: 'Children\'s Books',
  Christian_Books_Bibles: 'Christian Books & Bibles',
  Comics_Graphic_Novels: 'Comics & Graphic Novels',
  Computers_Technology: 'Computers & Technology',
  Cookbooks_Food_Wine: 'Cookbooks, Food & Wine',
  Crafts_Hobbies_Home: 'Crafts, Hobbies & Home',
  Education_Teaching: 'Education & Teaching',
  Engineering_Transportation: 'Engineering & Transportation',
  Health_Fitness_Dieting: 'Health, Fitness & Dieting',
  History: 'History',
  Humor_Entertainment: 'Humor & Entertainment',
  Law: 'Law',
  LGBTQ_Books: 'LGBTQ+ Books',
  Literature_Fiction: 'Literature & Fiction',
  Medical_Books: 'Medical Books',
  Mystery_Thriller_Suspense: 'Mystery, Thriller & Suspense',
  Parenting_Relationships: 'Parenting & Relationships',
  Politics_Social_Sciences: 'Politics & Social Sciences',
  Reference: 'Reference',
  Religion_Spirituality: 'Religion & Spirituality',
  Romance: 'Romance',
  Science_Math: 'Science & Math',
  Science_Fiction_Fantasy: 'Science Fiction & Fantasy',
  Self_Help: 'Self-Help',
  Sports_Outdoors: 'Sports & Outdoors',
  Teen_Young_Adult: 'Teen & Young Adult',
  Test_Preparation: 'Test Preparation',
  Travel: 'Travel',
};

export default {
  genre,
};